# make file generated by gryphel build system

include $(DEVKITARM)/3ds_rules

mk_COptionsCommon = -c -Wall -Wmissing-prototypes -Wno-uninitialized -Wundef -Wstrict-prototypes -mfloat-abi=hard -mtp=soft -march=armv6k -mtune=mpcore -Icfg/ -Isrc/
mk_COptionsOSGLU = $(mk_COptionsCommon) -Os
mk_COptions = $(mk_COptionsCommon) -Os

.PHONY: TheDefaultOutput clean

TheDefaultOutput : mnvm3ds.3dsx

bld/GLOBGLUE.o: src/GLOBGLUE.c cfg/CNFGGLOB.h
	$(DEVKITARM)/bin/arm-none-eabi-gcc "src/GLOBGLUE.c" -o "bld/GLOBGLUE.o" $(mk_COptions)
bld/M68KITAB.o: src/M68KITAB.c cfg/CNFGGLOB.h
	$(DEVKITARM)/bin/arm-none-eabi-gcc "src/M68KITAB.c" -o "bld/M68KITAB.o" $(mk_COptions)
bld/MINEM68K.o: src/MINEM68K.c src/FPMATHEM.h src/FPCPEMDV.h cfg/CNFGGLOB.h
	$(DEVKITARM)/bin/arm-none-eabi-gcc "src/MINEM68K.c" -o "bld/MINEM68K.o" $(mk_COptions)
bld/VIAEMDEV.o: src/VIAEMDEV.c cfg/CNFGGLOB.h
	$(DEVKITARM)/bin/arm-none-eabi-gcc "src/VIAEMDEV.c" -o "bld/VIAEMDEV.o" $(mk_COptions)
bld/VIA2EMDV.o: src/VIA2EMDV.c cfg/CNFGGLOB.h
	$(DEVKITARM)/bin/arm-none-eabi-gcc "src/VIA2EMDV.c" -o "bld/VIA2EMDV.o" $(mk_COptions)
bld/IWMEMDEV.o: src/IWMEMDEV.c cfg/CNFGGLOB.h
	$(DEVKITARM)/bin/arm-none-eabi-gcc "src/IWMEMDEV.c" -o "bld/IWMEMDEV.o" $(mk_COptions)
bld/SCCEMDEV.o: src/SCCEMDEV.c cfg/CNFGGLOB.h
	$(DEVKITARM)/bin/arm-none-eabi-gcc "src/SCCEMDEV.c" -o "bld/SCCEMDEV.o" $(mk_COptions)
bld/RTCEMDEV.o: src/RTCEMDEV.c cfg/CNFGGLOB.h
	$(DEVKITARM)/bin/arm-none-eabi-gcc "src/RTCEMDEV.c" -o "bld/RTCEMDEV.o" $(mk_COptions)
bld/ROMEMDEV.o: src/ROMEMDEV.c cfg/CNFGGLOB.h
	$(DEVKITARM)/bin/arm-none-eabi-gcc "src/ROMEMDEV.c" -o "bld/ROMEMDEV.o" $(mk_COptions)
bld/SCSIEMDV.o: src/SCSIEMDV.c cfg/CNFGGLOB.h
	$(DEVKITARM)/bin/arm-none-eabi-gcc "src/SCSIEMDV.c" -o "bld/SCSIEMDV.o" $(mk_COptions)
bld/SONYEMDV.o: src/SONYEMDV.c cfg/CNFGGLOB.h
	$(DEVKITARM)/bin/arm-none-eabi-gcc "src/SONYEMDV.c" -o "bld/SONYEMDV.o" $(mk_COptions)
bld/SCRNEMDV.o: src/SCRNEMDV.c cfg/CNFGGLOB.h
	$(DEVKITARM)/bin/arm-none-eabi-gcc "src/SCRNEMDV.c" -o "bld/SCRNEMDV.o" $(mk_COptions)
bld/VIDEMDEV.o: src/VIDEMDEV.c cfg/CNFGGLOB.h
	$(DEVKITARM)/bin/arm-none-eabi-gcc "src/VIDEMDEV.c" -o "bld/VIDEMDEV.o" $(mk_COptions)
bld/MOUSEMDV.o: src/MOUSEMDV.c cfg/CNFGGLOB.h
	$(DEVKITARM)/bin/arm-none-eabi-gcc "src/MOUSEMDV.c" -o "bld/MOUSEMDV.o" $(mk_COptions)
bld/ADBEMDEV.o: src/ADBEMDEV.c cfg/CNFGGLOB.h
	$(DEVKITARM)/bin/arm-none-eabi-gcc "src/ADBEMDEV.c" -o "bld/ADBEMDEV.o" $(mk_COptions)
bld/ASCEMDEV.o: src/ASCEMDEV.c cfg/CNFGGLOB.h
	$(DEVKITARM)/bin/arm-none-eabi-gcc "src/ASCEMDEV.c" -o "bld/ASCEMDEV.o" $(mk_COptions)
bld/PROGMAIN.o: src/PROGMAIN.c cfg/CNFGGLOB.h
	$(DEVKITARM)/bin/arm-none-eabi-gcc "src/PROGMAIN.c" -o "bld/PROGMAIN.o" $(mk_COptions)

ObjFiles = \
	bld/MINEM68K.o \
	bld/GLOBGLUE.o \
	bld/M68KITAB.o \
	bld/VIAEMDEV.o \
	bld/VIA2EMDV.o \
	bld/IWMEMDEV.o \
	bld/SCCEMDEV.o \
	bld/RTCEMDEV.o \
	bld/ROMEMDEV.o \
	bld/SCSIEMDV.o \
	bld/SONYEMDV.o \
	bld/SCRNEMDV.o \
	bld/VIDEMDEV.o \
	bld/MOUSEMDV.o \
	bld/ADBEMDEV.o \
	bld/ASCEMDEV.o \
	bld/PROGMAIN.o \


mnvm3ds.3dsx : $(ObjFiles)
	$(DEVKITARM)/bin/arm-none-eabi-gcc \
		-o "bld/mnvm3ds.elf" \
		$(ObjFiles) -L$(DEVKITPRO)/libctru/lib -specs=3dsx.specs -lcitro2d -lcitro3d -lctru -lm -mfloat-abi=hard -mtp=soft

clean :
	rm -f $(ObjFiles)
	rm -f "bld/mnvm3ds.elf"
	rm -f "bld/mnvm3ds.arm9"
	rm -f "mnvm3ds.3dsx"
