/*
	Configuration options used by platform specific code.

	This file is automatically generated by the build system,
	which tries to know what options are valid in what
	combinations. Avoid changing this file manually unless
	you know what you're doing.
*/

#include <3ds.h>
#include <citro3d.h>
#include <png.h>

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <dirent.h>

#define RomFileName "MacII.ROM"
#define EnableDragDrop 1
#define EnableAltKeysMode 0
#define SwapCommandControl 0
#define VarFullScreen 0
#define MayFullScreen 1
#define MayNotFullScreen 0
#define WantInitMagnify 0
#define EnableMagnify 0
#define UseColorImage 1
#define WantInitRunInBackground 0
#define WantInitNotAutoSlow 0
#define WantInitSpeedValue -1
#define NeedRequestInsertDisk 0
#define NeedDoMoreCommandsMsg 0
#define NeedDoAboutMsg 0
#define UseControlKeys 1
#define UseActvCode 0
#define EnableDemoMsg 0

/* version and other info to display to user */

#define NeedIntlChars 0
#define kStrAppName "Mini vMac"
#define kAppVariationStr "Mini vMac 3DS MacII-4bpp"
#define kStrCopyrightYear "2017"
#define kMaintainerName "Tara Keeling"
#define kStrHomePage "https://github.com/TaraHoleInIt"
